version: '3.8'

services:
    apache:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: apache
        ports:
            - "80:80"
        depends_on:
            - db
        volumes:
            - .:/var/www/html
            - ./logs/apache:/var/log/apache2
        networks:
            - app-network

    db:
        image: mysql:5.7
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: 1qAzxSw2
            MYSQL_DATABASE: crafters_bazaar
            MYSQL_USER: crafters_user
            MYSQL_PASSWORD: 1qAzxSw2
        ports:
            - "3307:3306"
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - app-network

volumes:
    db-data:

networks:
    app-network:
        driver: bridge
